version: 2.1

jobs:
    deploy:
    machine:
        enabled: true
    steps:
        - run:
            name: Deploy Over SSH
            command: |
              ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
              echo hello world

workflows:
    build-and-deploy:
    jobs:
        - deploy